// imported into ./main.js

export const navLinks = {
    links: [
        {
            to: "/shop",
            icon: "mdi-cart-arrow-down",
            text: "Shop",
            divider: true,
        },
        {
            to: "/dashboard",
            icon: "mdi-desktop-mac-dashboard",
            text: "Dashboard",
            divider: true,
        },
        {
            to: "/order_history",
            icon: "mdi-align-horizontal-left",
            text: "Order History",
            divider: true,
        },
        // {
        //     // to: "/order_history",
        //     icon: "mdi-apps",
        //     text: "Dashboard",
        //     divider: true,
        //     subLinks: [
        //         {
        //             to: "wholesale/dashboard",
        //             icon: "mdi-desktop-mac-dashboard",
        //             text: "Wholesale Dashboard",
        //             divider: true,
        //         },
        //     //     {
        //     //         to: "admin",
        //     //         icon: "mdi-desktop-mac-dashboard",
        //     //         text: "Admin",
        //     //         divider: true,
        //     //     },
        //     //     {
        //     //         to: "/retail",
        //     //         icon: "mdi-desktop-mac-dashboard",
        //     //         text: "Reatil",
        //     //         divider: true,
        //     //     },
        //     //     {
        //     //         to: "/wholesale",
        //     //         icon: "mdi-desktop-mac-dashboard",
        //     //         text: "Wholesale",
        //     //         divider: true,
        //     //     },
        //     ]
        // },
    ],
}

export const shippingConstants = {
    origin_criterion_list: ['A', 'B', 'C'],
    uom_list: ['EA', 'BOX', 'USG', 'LB'],
    hu_list: ['Can', 'Case', 'Box', 'Keg', 'Pail', 'Drum', 'Jug', 'Tote', 'Bucket'],
    vendor_list: ['nhou', 'lemmer'],
    active_list: [
        { abbr: '0', state: 'Not Active' },
        { abbr: '1', state: 'Active' },
    ],
}
export const collectionName = {
    products: 'products',
    shipto: 'shipto',
    orders: 'orders'
}
export const readRoutes = {
    // isActive: 'isActive=1',
    singleProduct: 'single_product',
    allProducts: 'all_products',
    // allActiveProducts: `all_products?isActive=1`,
    singleShipto: 'single_shipto',
    allShipto: 'all_shipto',
    singleOrder: 'single_order',
    allOrders: 'all_orders',
    aggregation: 'aggregation',
    orderQue: 'order_que',
}

export const crudQuery = {
    inventory: 'inventory',
    isActive: 'isActive',
    allProducts: 'allProducts'
}

export const vuetifyTableConstants = {
    productHeaders: [
        { text: "SKU", value: 'sku', align: 'start', width: '6%' },
        { text: "Description", value: 'description', align: 'start', width: '15%' },
        { text: "HS Code", value: 'hs_code', align: 'end', width: '6%' },
        { text: "Dimensions", value: 'package_dimensions', width: '6%', align: 'end' },
        { text: "Product Weight", value: 'product_weight_lbs', align: 'end' },
        { text: "Gross Weight", value: 'gross_weight_lbs', align: 'end' },
        { text: "Ship Weight", value: 'shipping_weight_lbs', align: 'end' },
        { text: "Orig Criterion", value: 'origin_criterion', align: 'end' },
        { text: "Orig Country", value: 'origin_country', align: 'end' },
        { text: "Ship Cost", value: 'shipping_cost_usd', align: 'end' },
        { text: "Per Unit Cost", value: 'per_unit_cost_usd', align: 'end' },
        { text: "Customer Cost", value: 'customer_cost_usd', align: 'end' },
        { text: "Units per SKU", value: 'units_per_sku', align: 'start' },
        { text: "UOM", value: 'unit_of_measure', align: 'start' },
        { text: "H/U", value: 'handling_unit', align: 'start' },
        { text: "Active", value: 'is_active', align: 'end' },
        { text: "Last Updated", value: 'last_updated', align: 'end' },
        { text: "Vendor", value: 'vendor', align: 'end' },
        { text: "Inventory", value: 'inventory.current_stock', align: 'end' },
        // { text: "Image URL", value: 'gcs_img_url' },
        { text: 'Actions', value: 'actions', sortable: false }
    ],

    shiptoHeaders: [
        { text: "Contact Name", value: 'name' },
        { text: "Company Name", value: 'company_name' },
        { text: "Country", value: 'country' },
        { text: "State/Province", value: 'state_province' },
        { text: "City", value: 'city_name' },
        { text: "Unit #", value: 'unit_number' },
        { text: "Street", value: 'street_name' },
        { text: "Street Type", value: 'street_type' },
        { text: "Phone #", value: 'phone' },
        { text: "Email", value: 'email' },
        { text: "Tax ID", value: 'tax_shipping_code' },
        { text: "Zip/Postal", value: 'zip_code' },
        { text: 'Actions', value: 'actions', sortable: false },
    ],
    shipmentHeaders: [
        { text: "SKU", value: "order_sku" },
        { text: "Date Submitted", value: "date_submitted" },
        { text: "Status", value: "status" },
        { text: "Description", value: "order_description" },
        { text: "Qty Ordered", value: "quantity" },
        { text: "Qty In Production", value: "quantity_fulfilled_count" },
        // { text: "Qty Shipped", value: 'order_quantity_shipped' },
        { text: "Add", value: "all_items", sortable: false },
    ],
    checkoutWholesaleHeaders: [
        { text: "SKU", value: 'product' },
        { text: "Description", value: 'description' },
        { text: "Unit Price $(USD)", value: 'price' },
        { text: "Qty", value: 'quantity' },
        { text: 'Sub-Total $(USD)', value: 'subtotal' },
        { text: "Shipping Date", value: 'shipping_date' },
        { text: 'Update', value: 'actions', sortable: false },
    ],
    checkoutRetailHeaders: [
        { text: "SKU", value: 'product' },
        { text: "Description", value: 'description' },
        { text: "Unit Price $(USD)", value: 'price' },
        { text: "Qty", value: 'quantity' },
        { text: 'Sub-Total $(USD)', value: 'subtotal' },
        { text: "Shipping Date", value: 'shipping_date' },
        { text: 'Update', value: 'actions', sortable: false },
    ],

}
export const formConstants = {
    country_list: ['U.S.A.', 'CANADA'],
    states_list: [
        { abbr: 'AK', state: 'Alaska' },
        { abbr: 'AL', state: 'Alabama' },
        { abbr: 'AR', state: 'Arkansas' },
        { abbr: 'AS', state: 'American Samoa' },
        { abbr: 'AZ', state: 'Arizona' },
        { abbr: 'CA', state: 'California' },
        { abbr: 'CO', state: 'Colorado' },
        { abbr: 'CT', state: 'Connecticut' },
        { abbr: 'DC', state: 'District of Columbia' },
        { abbr: 'DE', state: 'Delaware' },
        { abbr: 'FL', state: 'Florida' },
        { abbr: 'GA', state: 'Georgia' },
        { abbr: 'GU', state: 'Guam' },
        { abbr: 'HI', state: 'Hawaii' },
        { abbr: 'IA', state: 'Iowa' },
        { abbr: 'ID', state: 'Idaho' },
        { abbr: 'IL', state: 'Illinois' },
        { abbr: 'IN', state: 'Indiana' },
        { abbr: 'KS', state: 'Kansas' },
        { abbr: 'KY', state: 'Kentucky' },
        { abbr: 'LA', state: 'Louisiana' },
        { abbr: 'MA', state: 'Massachusetts' },
        { abbr: 'MD', state: 'Maryland' },
        { abbr: 'ME', state: 'Maine' },
        { abbr: 'MI', state: 'Michigan' },
        { abbr: 'MN', state: 'Minnesota' },
        { abbr: 'MO', state: 'Missouri' },
        { abbr: 'MP', state: 'Northern Mariana Islands' },
        { abbr: 'MS', state: 'Mississippi' },
        { abbr: 'MT', state: 'Montana' },
        { abbr: 'NA', state: 'National' },
        { abbr: 'NC', state: 'North Carolina' },
        { abbr: 'ND', state: 'North Dakota' },
        { abbr: 'NE', state: 'Nebraska' },
        { abbr: 'NH', state: 'New Hampshire' },
        { abbr: 'NJ', state: 'New Jersey' },
        { abbr: 'NM', state: 'New Mexico' },
        { abbr: 'NV', state: 'Nevada' },
        { abbr: 'NY', state: 'New York' },
        { abbr: 'OH', state: 'Ohio' },
        { abbr: 'OK', state: 'Oklahoma' },
        { abbr: 'OR', state: 'Oregon' },
        { abbr: 'PA', state: 'Pennsylvania' },
        { abbr: 'PR', state: 'Puerto Rico' },
        { abbr: 'RI', state: 'Rhode Island' },
        { abbr: 'SC', state: 'South Carolina' },
        { abbr: 'SD', state: 'South Dakota' },
        { abbr: 'TN', state: 'Tennessee' },
        { abbr: 'TX', state: 'Texas' },
        { abbr: 'UT', state: 'Utah' },
        { abbr: 'VA', state: 'Virginia' },
        { abbr: 'VI', state: 'Virgin Islands' },
        { abbr: 'VT', state: 'Vermont' },
        { abbr: 'WA', state: 'Washington' },
        { abbr: 'WI', state: 'Wisconsin' },
        { abbr: 'WV', state: 'West Virginia', },
        { abbr: 'WY', state: 'Wyoming' },
        { abbr: 'ON', state: 'Ontario' },
        { abbr: 'AB', state: 'Alberta' },
        { abbr: 'BC', state: 'British Columbia' },
        { abbr: 'SK', state: 'Saskatchewan' },
        { abbr: 'MB', state: 'Manitoba' },
        { abbr: 'QC', state: 'Quebec' },
        { abbr: 'NL', state: 'Newfoundland Labrador' },
        { abbr: 'YT', state: 'Yukon' },
        { abbr: 'NU', state: 'Nunavut' },
        { abbr: 'NT', state: 'Northwest Territories' }
    ]
}

